#!/usr/bin/env python3
"""Rebuild notebooks/kinesis_comparison.ipynb (GT vs MuscleMAP vs Kinesis)."""
from __future__ import annotations

import json
from pathlib import Path


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": [text]}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [text],
    }


NB = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "musclemap-bench", "language": "python", "name": "python3"},
        "language_info": {"name": "python"},
    },
    "cells": [
        md(
            "# Сравнение: ground truth, MuscleMAP и Kinesis\n\n"
            "Эта тетрадка работает из корня **`musclemap-bench`**.\n\n"
            "Показывает:\n"
            "1. Список движений, для которых есть артефакты Kinesis (`data/kinesis_artifacts/_manifest.json`).\n"
            "2. **Анимацию** (MP4/GIF) одного и того же SMPL-X движения: GT · MuscleMAP · Kinesis, кости по активациям.\n"
            "3. Таблицу метрик L1 (MAE, RMSE, DTW-MAE, Pearson r, R²) для MuscleMAP и Kinesis "
            "относительно ground truth на **42 сопоставимых мышцах ног**.\n\n"
            "Предварительно:\n"
            "```bash\n"
            "conda activate musclemap-bench\n"
            "python precompute/run_kinesis.py --config config.yaml --test-split-only  # если ещё не запускали\n"
            "```"
        ),
        code(
            "from __future__ import annotations\n\n"
            "import json\n"
            "import logging\n"
            "import sys\n"
            "from pathlib import Path\n\n"
            "import matplotlib.pyplot as plt\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "from IPython.display import Image, Video, display, Markdown\n"
            "from mpl_toolkits.mplot3d import Axes3D  # noqa: F401\n\n"
            "logging.basicConfig(level=logging.INFO, format=\"%(levelname)s %(message)s\")\n\n"
            "REPO_ROOT = Path.cwd()\n"
            "if not (REPO_ROOT / \"config.yaml\").exists() and (REPO_ROOT.parent / \"config.yaml\").exists():\n"
            "    REPO_ROOT = REPO_ROOT.parent\n"
            "if str(REPO_ROOT) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO_ROOT))\n\n"
            "from src.align import align_lengths, build_mapping_kinesis_artifacts\n"
            "from src.body_visualization import (\n"
            "    create_triple_activation_animation,\n"
            "    save_animation_media,\n"
            ")\n"
            "from src.inference import run_kinesis_from_artifact, run_musclemap\n"
            "from src.loaders import (\n"
            "    get_benchmark_sample,\n"
            "    load_config,\n"
            "    load_kinesis_manifest,\n"
            "    load_kinesis_muscle_names,\n"
            "    load_musclemap,\n"
            "    load_test_dataset,\n"
            ")\n"
            "from src.metrics_l1 import aggregate_l1_metrics, compute_l1_metrics\n"
            "from src.paired_eval import (\n"
            "    ensure_vis_examples,\n"
            "    list_paired_indices,\n"
            "    paired_coverage_stats,\n"
            ")\n"
            "from precompute.run_kinesis import RAJAGOPAL_TO_KINESIS_ACTUATOR\n\n"
            "cfg = load_config(REPO_ROOT / \"config.yaml\")\n"
            "DEVICE = str(cfg.get(\"inference\", {}).get(\"device\", \"cpu\"))\n"
            "VIS_SEQUENCE_ID = \"Simultaneously_Waddling_and_walking_clip1\"  # анимация в §4\n"
            "MAX_VIS = 1          # сколько примеров визуализировать\n"
            "VIS_FPS = 12         # кадров/с в MP4/GIF\n"
            "VIS_FRAME_STEP = 1   # 2 = каждый второй кадр (быстрее рендер)\n"
            "MAX_EVAL = None      # None = все paired окна; или int для быстрого прогона\n"
            "CHECKPOINT = None    # None = config paths.musclemap_checkpoint\n\n"
            "print(f\"Repo: {REPO_ROOT}\")\n"
            "print(f\"Device: {DEVICE}\")"
        ),
        md("## 1. Список движений, обработанных Kinesis"),
        code(
            "manifest_raw = json.loads(\n"
            "    (REPO_ROOT / \"data/kinesis_artifacts/_manifest.json\").read_text(encoding=\"utf-8\")\n"
            ")\n"
            "k_manifest = load_kinesis_manifest(cfg)\n\n"
            "rows = []\n"
            "for seq_id, info in sorted(manifest_raw.items()):\n"
            "    rows.append({\n"
            "        \"sequence_id\": seq_id,\n"
            "        \"status\": info.get(\"status\", \"?\"),\n"
            "        \"timing_s\": info.get(\"timing_s\"),\n"
            "        \"file\": info.get(\"file\"),\n"
            "        \"error\": info.get(\"error\"),\n"
            "    })\n"
            "manifest_df = pd.DataFrame(rows)\n"
            "ok_df = manifest_df[manifest_df[\"status\"] == \"ok\"].copy()\n"
            "err_df = manifest_df[manifest_df[\"status\"] != \"ok\"].copy()\n\n"
            "display(Markdown(\n"
            "    f\"**Всего записей в manifest:** {len(manifest_df)} · \"\n"
            "    f\"**успешно (ok):** {len(ok_df)} · **ошибки:** {len(err_df)}\"\n"
            "))\n"
            "display(ok_df[[\"sequence_id\", \"timing_s\", \"file\"]].head(20))\n"
            "if len(ok_df) > 20:\n"
            "    display(Markdown(f\"… и ещё {len(ok_df) - 20} успешных записей (см. `ok_df`)\"))\n"
            "if len(err_df):\n"
            "    display(Markdown(\"#### Ошибки precompute\"))\n"
            "    display(err_df[[\"sequence_id\", \"error\"]].head(10))"
        ),
        md("## 2. Paired test-окна (есть и GT, и Kinesis)"),
        code(
            "dataset, rajagopal_names = load_test_dataset(cfg)\n"
            "k_names = load_kinesis_muscle_names(cfg)\n"
            "mapping = build_mapping_kinesis_artifacts(rajagopal_names, k_names, RAJAGOPAL_TO_KINESIS_ACTUATOR)\n\n"
            "paired_indices = list_paired_indices(dataset, k_manifest)\n"
            "if MAX_EVAL is not None:\n"
            "    paired_indices = paired_indices[: int(MAX_EVAL)]\n\n"
            "coverage = paired_coverage_stats(dataset, k_manifest)\n"
            "display(Markdown(\n"
            "    f\"- Test окон: **{coverage['n_test_windows']}**\\n\"\n"
            "    f\"- Paired окон (Kinesis): **{coverage['n_paired_windows']}**\\n\"\n"
            "    f\"- Уникальных test-последовательностей: **{coverage['n_test_sequences']}**\\n\"\n"
            "    f\"- С Kinesis: **{coverage['n_paired_sequences']}**\\n\"\n"
            "    f\"- Сопоставимых мышц: **{len(mapping.shared_names)}**\"\n"
            "))\n\n"
            "model = load_musclemap(cfg, device=DEVICE, checkpoint_path=CHECKPOINT)\n"
            "print(f\"Loaded MuscleMAP on {DEVICE}\")"
        ),
        md("## 3. Метрики по каждому paired-движению"),
        code(
            "layer1 = cfg[\"layer1\"]\n"
            "metric_kw = dict(\n"
            "    dtw_enabled=layer1[\"dtw_enabled\"],\n"
            "    dtw_radius=layer1[\"dtw_radius\"],\n"
            "    activation_threshold=layer1[\"activation_threshold\"],\n"
            "    min_active_frames=layer1[\"min_active_frames\"],\n"
            "    compute_coactivation=False,\n"
            ")\n\n"
            "def _expand_to_rajagopal(mapped: np.ndarray, raj_indices: list[int], n: int = 80) -> np.ndarray:\n"
            "    out = np.zeros((mapped.shape[0], n), dtype=np.float32)\n"
            "    for j, r_idx in enumerate(raj_indices):\n"
            "        out[:, int(r_idx)] = mapped[:, j]\n"
            "    return out\n\n"
            "def _load_smplx_window(ds, idx: int) -> np.ndarray:\n"
            "    seq_dir, start, true_T, _text = ds._items[idx]\n"
            "    motion = np.load(seq_dir / \"smplx_322.npy\").astype(np.float32)\n"
            "    return motion[int(start) : int(start) + int(true_T)]\n\n"
            "mm_metrics_list: list[dict] = []\n"
            "kin_metrics_list: list[dict] = []\n"
            "per_row: list[dict] = []\n"
            "examples: list[dict] = []\n\n"
            "for idx in paired_indices:\n"
            "    sample = get_benchmark_sample(dataset, idx)\n"
            "    seq_id = sample.sequence_id\n"
            "    ref = sample.activations\n\n"
            "    mm = run_musclemap(model, sample.text, seq_id, device=DEVICE, ref_T=ref.shape[0])\n"
            "    kin = run_kinesis_from_artifact(k_manifest[seq_id][\"path\"], seq_id, sample.text)\n\n"
            "    mm_pred, ref_a = align_lengths(mm.activations, ref)\n"
            "    kin_pred = kin.activations[:, mapping.kinesis_indices]\n"
            "    kin_ref = ref[:, mapping.rajagopal_indices]\n"
            "    kin_pred, kin_ref = align_lengths(kin_pred, kin_ref)\n\n"
            "    mm_p = mm_pred[:, mapping.rajagopal_indices]\n"
            "    kin_p = kin_pred\n"
            "    ref_p = ref_a[:, mapping.rajagopal_indices]\n\n"
            "    mm_m = compute_l1_metrics(mm_p, ref_p, mapping.shared_names, **metric_kw)\n"
            "    kin_m = compute_l1_metrics(kin_p, kin_ref, mapping.shared_names, **metric_kw)\n"
            "    mm_metrics_list.append(mm_m)\n"
            "    kin_metrics_list.append(kin_m)\n\n"
            "    per_row.append({\n"
            "        \"sequence_id\": seq_id,\n"
            "        \"prompt\": sample.text,\n"
            "        \"n_frames\": mm_m[\"n_frames\"],\n"
            "        \"mm_mae\": mm_m[\"mae\"],\n"
            "        \"mm_rmse\": mm_m[\"rmse\"],\n"
            "        \"mm_dtw_mae\": mm_m.get(\"dtw_mae\"),\n"
            "        \"mm_pearson_r\": mm_m[\"pearson_r_mean\"],\n"
            "        \"mm_r2\": mm_m[\"r2_mean\"],\n"
            "        \"kin_mae\": kin_m[\"mae\"],\n"
            "        \"kin_rmse\": kin_m[\"rmse\"],\n"
            "        \"kin_dtw_mae\": kin_m.get(\"dtw_mae\"),\n"
            "        \"kin_pearson_r\": kin_m[\"pearson_r_mean\"],\n"
            "        \"kin_r2\": kin_m[\"r2_mean\"],\n"
            "        \"kin_timing_s\": float(k_manifest[seq_id].get(\"timing_s\", float(\"nan\"))),\n"
            "        \"mm_timing_s\": float(mm.timing_s),\n"
            "    })\n\n"
            "    if seq_id == VIS_SEQUENCE_ID and len(examples) < MAX_VIS:\n"
            "        smplx_win = _load_smplx_window(dataset, idx)\n"
            "        T = min(smplx_win.shape[0], mm_pred.shape[0], kin_pred.shape[0], ref_a.shape[0])\n"
            "        examples.append({\n"
            "            \"sequence_id\": seq_id,\n"
            "            \"prompt\": sample.text,\n"
            "            \"smplx\": smplx_win[:T],\n"
            "            \"gt\": ref_a[:T],\n"
            "            \"mm\": mm_pred[:T],\n"
            "            \"kin_full\": _expand_to_rajagopal(kin_p[:T], mapping.rajagopal_indices, len(rajagopal_names)),\n"
            "        })\n\n"
            "metrics_df = pd.DataFrame(per_row).sort_values(\"mm_mae\").reset_index(drop=True)\n"
            "agg_mm = aggregate_l1_metrics(mm_metrics_list)\n"
            "agg_kin = aggregate_l1_metrics(kin_metrics_list)\n\n"
            "summary_df = pd.DataFrame([\n"
            "    {\n"
            "        \"method\": \"MuscleMAP\",\n"
            "        \"n_windows\": agg_mm.get(\"n_samples\"),\n"
            "        \"mae\": agg_mm.get(\"mae\"),\n"
            "        \"rmse\": agg_mm.get(\"rmse\"),\n"
            "        \"dtw_mae\": agg_mm.get(\"dtw_mae\"),\n"
            "        \"pearson_r_mean\": agg_mm.get(\"pearson_r_mean\"),\n"
            "        \"r2_mean\": agg_mm.get(\"r2_mean\"),\n"
            "        \"smoothness_pred\": agg_mm.get(\"smoothness_pred\"),\n"
            "    },\n"
            "    {\n"
            "        \"method\": \"Kinesis\",\n"
            "        \"n_windows\": agg_kin.get(\"n_samples\"),\n"
            "        \"mae\": agg_kin.get(\"mae\"),\n"
            "        \"rmse\": agg_kin.get(\"rmse\"),\n"
            "        \"dtw_mae\": agg_kin.get(\"dtw_mae\"),\n"
            "        \"pearson_r_mean\": agg_kin.get(\"pearson_r_mean\"),\n"
            "        \"r2_mean\": agg_kin.get(\"r2_mean\"),\n"
            "        \"smoothness_pred\": agg_kin.get(\"smoothness_pred\"),\n"
            "    },\n"
            "])\n\n"
            "display(Markdown(\"### Сводка по всем paired-окнам (vs OpenSim GT)\"))\n"
            "display(summary_df.style.format({\n"
            "    \"mae\": \"{:.5f}\", \"rmse\": \"{:.5f}\", \"dtw_mae\": \"{:.5f}\",\n"
            "    \"pearson_r_mean\": \"{:.4f}\", \"r2_mean\": \"{:.4f}\", \"smoothness_pred\": \"{:.5f}\",\n"
            "}, na_rep=\"—\"))\n\n"
            "display(Markdown(\"### По каждому движению (первые 25 строк)\"))\n"
            "show_cols = [\n"
            "    \"sequence_id\", \"n_frames\",\n"
            "    \"mm_mae\", \"kin_mae\", \"mm_rmse\", \"kin_rmse\",\n"
            "    \"mm_pearson_r\", \"kin_pearson_r\", \"mm_r2\", \"kin_r2\",\n"
            "]\n"
            "display(metrics_df[show_cols].head(25).style.format({\n"
            "    c: \"{:.5f}\" for c in show_cols if c not in (\"sequence_id\", \"n_frames\")\n"
            "}))\n\n"
            "examples = ensure_vis_examples(\n"
            "    examples,\n"
            "    VIS_SEQUENCE_ID,\n"
            "    max_vis=MAX_VIS,\n"
            "    cfg=cfg,\n"
            "    dataset=dataset,\n"
            "    model=model,\n"
            "    k_manifest=k_manifest,\n"
            "    mapping=mapping,\n"
            "    rajagopal_names=rajagopal_names,\n"
            "    device=DEVICE,\n"
            ")\n"
            "if examples:\n"
            "    print(f\"Vis example: {examples[-1]['sequence_id']} ({examples[-1]['smplx'].shape[0]} frames)\")\n"
            "else:\n"
            "    print(f\"Warning: could not build vis example for {VIS_SEQUENCE_ID!r}\")"
        ),
        md(
            "## 4. Анимации (GT · MuscleMAP · Kinesis)\n\n"
            "Сохраняются в `results/plots/triple_<sequence_id>.mp4` (или `.gif`, если нет ffmpeg). "
            "Параметры `VIS_FPS` и `VIS_FRAME_STEP` — в первой ячейке."
        ),
        code(
            "plots_dir = REPO_ROOT / \"results\" / \"plots\"\n"
            "plots_dir.mkdir(parents=True, exist_ok=True)\n\n"
            "examples = ensure_vis_examples(\n"
            "    examples,\n"
            "    VIS_SEQUENCE_ID,\n"
            "    max_vis=MAX_VIS,\n"
            "    cfg=cfg,\n"
            "    dataset=dataset,\n"
            "    model=model,\n"
            "    k_manifest=k_manifest,\n"
            "    mapping=mapping,\n"
            "    rajagopal_names=rajagopal_names,\n"
            "    device=DEVICE,\n"
            ")\n"
            "if not examples:\n"
            "    raise RuntimeError(\n"
            "        f\"No visualization data for {VIS_SEQUENCE_ID!r}. \"\n"
            "        \"Run the model-load cell and check Kinesis manifest / test split.\"\n"
            "    )\n\n"
            "for ex in examples:\n"
            "    title = f\"{ex['sequence_id']}\\n{ex['prompt'][:80]}\"\n"
            "    anim = create_triple_activation_animation(\n"
            "        ex[\"smplx\"],\n"
            "        ex[\"gt\"],\n"
            "        ex[\"mm\"],\n"
            "        ex[\"kin_full\"],\n"
            "        rajagopal_names,\n"
            "        fps=VIS_FPS,\n"
            "        frame_step=VIS_FRAME_STEP,\n"
            "        title=title,\n"
            "    )\n"
            "    out_path = plots_dir / f\"triple_{ex['sequence_id']}.mp4\"\n"
            "    saved = save_animation_media(anim, out_path, fps=VIS_FPS)\n"
            "    print(f\"Saved {saved}\")\n\n"
            "    if saved.suffix.lower() == \".mp4\":\n"
            "        display(Video(str(saved), embed=True, html_attributes=\"controls autoplay loop\"))\n"
            "    else:\n"
            "        display(Image(filename=str(saved)))\n"
            "    display(Markdown(\"---\"))\n"
        ),
        md("## 5. Экспорт таблицы"),
        code(
            "out_csv = REPO_ROOT / \"results\" / \"kinesis_triple_comparison.csv\"\n"
            "metrics_df.to_csv(out_csv, index=False)\n"
            "summary_csv = REPO_ROOT / \"results\" / \"kinesis_triple_summary.csv\"\n"
            "summary_df.to_csv(summary_csv, index=False)\n"
            "display(Markdown(f\"Saved:\\n- `{out_csv}`\\n- `{summary_csv}`\"))"
        ),
    ],
}


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "notebooks" / "kinesis_comparison.ipynb"
    out.write_text(json.dumps(NB, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
